vim.keymap.set("n", "<leader>qf", function() vim.lsp.buf.code_action() end)
vim.keymap.set("n", "<leader>th" , function()
  vim.cmd('vertical terminal zsh')
  vim.cmd('startinsert')
end)
vim.keymap.set("n", "<C-f>", function()
  if require('nvim-tree.view').is_visible()
  then vim.cmd('NvimTreeClose')
  else vim.cmd('NvimTreeOpen')
  end
end)
